### PR TITLE
Non-orthogonal unit cell additions

### PR DESCRIPTION
**Pull request by costrouc**
These are additions of the non-unit cell class but does not actually add the non-orthogonal class to Container. And all of the changes to many of the lines is that my editor removed all the whitespace at the end of lines.

We will need to discuss how to move forward with including `ContainerPeriodic` and `ContainerPeriodicPoly` to the class `Container`.

### CODE REVIEW

**Comment by costrouc** [comment]
Would you be willing to make numpy a requirement?

I ask because it would make it much easier to make the logic for non-orthogonal cells since I will need to deal with vectors. I see that you use numpy and scipy throughout your code and I feel that most users will have numpy and scipy. In fact scipy has a voronoi module

**Comment by wackywendell** [comment]
Hi @costrouc,

My apologies for the very delayed response; in June 2016 I was just finishing my dissertation and working on getting a job, and maintenance of this repo very much fell through the cracks. Having just come back to it, I think this could make sense.

Having never needed a non-orthogonal container myself, I hadn't considered that, and only just now read up on the purpose of `ContainerPeriodic` in the voro++ code. I think that could be a useful addition, and your code looks like a good starting place for that. I'm going to investigate a bit, and look into what a constructor for this would look like; suggestions welcome if you have thoughts there.

**Comment by costrouc** [comment]
@wackywendell It has been awhile since I have written this code so I am not as familiar. I would be happy to make this PR compatible if there is interest. 

On another note tess is now packaged for nixos https://github.com/NixOS/nixpkgs/pull/61101

**Comment by SiyuChern** [comment]
Dear both @costrouc @wackywendell, I am really interested in the feature of non-orthogonal periodic containers. Is there still some probability to revive this pull request and move forward?

**Comment by costrouc** [comment]
@SiyuChen it has been a long time for me and I'm not likely to work on it. Feel free to continue this work with a new PR!

**Pull request closed without merging**
